#!/bin/bash

INI_PATH=/opt/mumble/mumble-server.ini

chown -R mumble-server:mumble-server /opt/mumble
sleep 2
if [ -n "$SUPERUSER_PASSWORD" ]; then
    sudo -u mumble-server /usr/sbin/murmurd -ini $INI_PATH -supw $SUPERUSER_PASSWORD
fi
sudo -u mumble-server /usr/sbin/murmurd -ini $INI_PATH -fg -v
